name: Build and Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build Lint Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 10.11.0

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm turbo run lint

      - name: Build
        run: pnpm turbo run build
        env:
          NODE_ENV: production
          VITE_EO_CLOUD_API_DOMAIN: ci-api.example.com
          VITE_BIO_S3_BUCKET_NAME: ci-example-bucket
          PASSTHROUGH_SOME_CREDENTIAL: this-will-not-be-replaced

      - name: Type Check
        run: |
          echo "Running TypeScript type check for all packages..."
          pnpm run typecheck

      - name: Run tests with coverage
        run: pnpm turbo run test -- --coverage

      - name: Install lcov
        run: sudo apt-get update && sudo apt-get install -y lcov

      - name: Upload coverage reports as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            packages/*/coverage/
            apps/*/coverage/
          retention-days: 7

      - name: Generate combined coverage report
        run: |
          # Create a directory for the combined report
          mkdir -p combined-coverage

          # Find and combine all lcov.info files
          find . -name "lcov.info" -exec echo -a {} \; | xargs lcov -o combined-coverage/lcov.info

          # Generate HTML report from combined lcov data
          genhtml combined-coverage/lcov.info --output-directory combined-coverage/html

      - name: Publish coverage report
        uses: actions/upload-artifact@v4
        with:
          name: combined-coverage-report
          path: combined-coverage/html
          retention-days: 7

      - name: Coverage Report Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: combined-coverage/lcov.info # Ensure this path is correct
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: markdown # Changed from 'both' to 'markdown'
          thresholds: "60 80"

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          header: Coverage Report
          recreate: true
          path: code-coverage-results.md # Ensure this file is generated by the previous step
